version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: quantcrux-postgres
    environment:
      POSTGRES_DB: quantcrux
      POSTGRES_USER: quantcrux
      POSTGRES_PASSWORD: quantcrux123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - quantcrux-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quantcrux"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Apache Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: quantcrux-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - quantcrux-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: quantcrux-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - quantcrux-network

  # Eureka Server
  eureka-server:
    build:
      context: ./backend/eureka-server
      dockerfile: Dockerfile
    container_name: quantcrux-eureka
    ports:
      - "8761:8761"
    networks:
      - quantcrux-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 60s

  # Gateway Service
  gateway-service:
    build:
      context: ./backend/gateway-service
      dockerfile: Dockerfile
    container_name: quantcrux-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - auth-service
    networks:
      - quantcrux-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Auth Service
  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: quantcrux-auth
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - eureka-server
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_auth
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/auth/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Strategy Service
  strategy-service:
    build:
      context: ./backend/strategy-service
      dockerfile: Dockerfile
    container_name: quantcrux-strategy
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - postgres    
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_strategy
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s


  # Market Data Service
  market-data-service:
    build:
      context: ./backend/market-data-service
      dockerfile: Dockerfile
    container_name: quantcrux-market-data
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server    
    networks:
      - quantcrux-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # User Service
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: quantcrux-user
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_user
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Backtest Service
  backtest-service:
    build:
      context: ./backend/backtest-service
      dockerfile: Dockerfile
    container_name: quantcrux-backtest
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_backtest
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Product Service
  product-service:
    build:
      context: ./backend/product-service
      dockerfile: Dockerfile
    container_name: quantcrux-product
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_product
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Portfolio Service
  portfolio-service:
    build:
      context: ./backend/portfolio-service
      dockerfile: Dockerfile
    container_name: quantcrux-portfolio
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_portfolio
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Analytics Service
  analytics-service:
    build:
      context: ./backend/analytics-service
      dockerfile: Dockerfile
    container_name: quantcrux-analytics
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_analytics
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Reporting Service
  reporting-service:
    build:
      context: ./backend/reporting-service
      dockerfile: Dockerfile
    container_name: quantcrux-reporting
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_reporting
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Booking Service
  booking-service:
    build:
      context: ./backend/booking-service
      dockerfile: Dockerfile
    container_name: quantcrux-booking
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
      - postgres
      - kafka
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_booking
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Lifecycle Service
  lifecycle-service:
    build:
      context: ./backend/lifecycle-service
      dockerfile: Dockerfile
    container_name: quantcrux-lifecycle
    ports:
      - "8091:8091"
    depends_on:
      - eureka-server
      - postgres
      - kafka
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_lifecycle
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Pricing Engine
  pricing-engine:
    build:
      context: ./backend/pricing-engine
      dockerfile: Dockerfile
    container_name: quantcrux-pricing
    ports:
      - "8092:8092"
    depends_on:
      - eureka-server
      - postgres
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_pricing
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgres_data:

networks:
  quantcrux-network:
    driver: bridge